# Generated by Django 5.2.15 on 2026-06-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('entreprise_souhaitee', models.CharField(help_text="Entreprise que le demandeur déclare. L'admin vérifie et choisit le client réel au moment de créer le compte.", max_length=120)),
                ('motivation', models.TextField(help_text='Pourquoi cette personne souhaite-t-elle déposer des images ?')),
                ('statut', models.CharField(choices=[('ATTENTE', 'En attente de traitement'), ('APPROUVEE', 'Approuvée (compte créé)'), ('REFUSEE', 'Refusée')], default='ATTENTE', max_length=10)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('traitee_le', models.DateTimeField(blank=True, null=True)),
                ('note_admin', models.CharField(blank=True, help_text='Note interne (ex : motif de refus, client attribué).', max_length=200)),
            ],
            options={
                'verbose_name': "Demande d'inscription",
                'verbose_name_plural': "Demandes d'inscription",
                'ordering': ['-date_demande'],
            },
        ),
    ]
