# Generated by Django 5.2.15 on 2026-06-11 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_demandeinscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('zip_reference', models.FileField(upload_to='batches/reference/%Y/%m/')),
                ('zip_travail', models.FileField(blank=True, null=True, upload_to='batches/travail/%Y/%m/')),
                ('nb_images', models.PositiveIntegerField(default=0)),
                ('statut', models.CharField(choices=[('A_FAIRE', 'À labéliser'), ('EN_COURS', 'En cours'), ('SOUMIS', 'Soumis (en attente de contrôle)'), ('VALIDE', 'Validé'), ('A_CORRIGER', 'À corriger')], default='A_FAIRE', max_length=12)),
                ('score_qualite', models.FloatField(blank=True, null=True)),
                ('rapport', models.JSONField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_soumission', models.DateTimeField(blank=True, null=True)),
                ('assigne_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches_assignes', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='core.client')),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lot de travail',
                'verbose_name_plural': 'Lots de travail',
                'ordering': ['-date_creation'],
            },
        ),
    ]
