# Generated by Django 5.2.15 on 2026-08-01 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Data scientist qui encadre ce contributeur (uniquement pour les contributeurs).', limit_choices_to={'role': 'DS'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributeurs', to=settings.AUTH_USER_MODEL),
        ),
    ]
